name: Build

on: [push, pull_request]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      -
        name: Check out code into the Go module directory
        uses: actions/checkout@master

      -
        name: Get dependencies
        run: |
          go get -v -d ./...
          go get -u golang.org/x/lint/golint
          go list -f {{.Target}} golang.org/x/lint/golint

      -
        name: Lint Go Code
        run: /home/runner/go/bin/golint ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Build
        run: make build