base:
    proxy: "socks5://host-bwg-new.aaqq.in:8096"
    socket: "host-bwg-new.aaqq.in:8096"
media:
    library: nfo
    url: "http://home.shixinyi.cn:38096"
    api: "f948875225934657b672ae63b2abc6c9"
    secretid: ""
    secretkey: ""
path:
    success: jav
    fail: fail
    directory: '{actor}/[{year}] {title}'
    filter: -hd||hd-||_hd||hd_||[||]||【||】||asfur||~||-full||_full||3xplanet||monv||云中飘荡||@||tyhg999.com||xxxxxxxx||-fhd||_fhd||thz.la
site:
    javbus: https://www.javbus.com/
    javdb: https://javdb.com/
