base:
    proxy: "socks5://host-bwg-new.aaqq.com:8096"
    socket: "host-bwg-new.aaqq.com:8096"
media:
    library: nfo
    url: "http://192.168.3.1:8096"
    api: "b7215f93f69f447c69997028ccae726fa"
    secretid: ""
    secretkey: ""
path:
    success: jav
    fail: fail
    directory: '{actor}/[{year}] {title}'
    filter: -hd||hd-||_hd||hd_||[||]||【||】||asfur||~||-full||_full||3xplanet||monv||云中飘荡||@||tyhg999.com||xxxxxxxx||-fhd||_fhd||thz.la
site:
    javbus: https://www.javbus.com/
    javdb: https://javdb4.com/
